# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MBI_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MBI_GUI(object):
    def setupUi(self, MBI_GUI):
        MBI_GUI.setObjectName("MBI_GUI")
        MBI_GUI.setEnabled(True)
        MBI_GUI.resize(1920, 1080)
        MBI_GUI.setWindowOpacity(1.0)
        MBI_GUI.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MBI_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadBitFile = QtWidgets.QPushButton(self.centralwidget)
        self.LoadBitFile.setGeometry(QtCore.QRect(30, 30, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LoadBitFile.setFont(font)
        self.LoadBitFile.setObjectName("LoadBitFile")
        self.LoadPattFile = QtWidgets.QPushButton(self.centralwidget)
        self.LoadPattFile.setGeometry(QtCore.QRect(30, 130, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LoadPattFile.setFont(font)
        self.LoadPattFile.setObjectName("LoadPattFile")
        self.Exposure = QtWidgets.QLineEdit(self.centralwidget)
        self.Exposure.setGeometry(QtCore.QRect(280, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Exposure.setFont(font)
        self.Exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Exposure.setObjectName("Exposure")
        self.exposurelabel = QtWidgets.QLabel(self.centralwidget)
        self.exposurelabel.setGeometry(QtCore.QRect(30, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exposurelabel.setFont(font)
        self.exposurelabel.setObjectName("exposurelabel")
        self.maskslabel = QtWidgets.QLabel(self.centralwidget)
        self.maskslabel.setGeometry(QtCore.QRect(30, 290, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskslabel.setFont(font)
        self.maskslabel.setObjectName("maskslabel")
        self.Masks = QtWidgets.QLineEdit(self.centralwidget)
        self.Masks.setGeometry(QtCore.QRect(280, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Masks.setFont(font)
        self.Masks.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Masks.setObjectName("Masks")
        self.MaskChanges = QtWidgets.QLineEdit(self.centralwidget)
        self.MaskChanges.setGeometry(QtCore.QRect(280, 350, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MaskChanges.setFont(font)
        self.MaskChanges.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaskChanges.setObjectName("MaskChanges")
        self.maskschangeslabel = QtWidgets.QLabel(self.centralwidget)
        self.maskschangeslabel.setGeometry(QtCore.QRect(30, 350, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskschangeslabel.setFont(font)
        self.maskschangeslabel.setObjectName("maskschangeslabel")
        self.maskschangeslabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.maskschangeslabel_2.setGeometry(QtCore.QRect(30, 410, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maskschangeslabel_2.setFont(font)
        self.maskschangeslabel_2.setObjectName("maskschangeslabel_2")
        self.SubChange = QtWidgets.QLineEdit(self.centralwidget)
        self.SubChange.setGeometry(QtCore.QRect(280, 410, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SubChange.setFont(font)
        self.SubChange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SubChange.setObjectName("SubChange")
        self.DispImage = QtWidgets.QPushButton(self.centralwidget)
        self.DispImage.setGeometry(QtCore.QRect(30, 470, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DispImage.setFont(font)
        self.DispImage.setCheckable(True)
        self.DispImage.setObjectName("DispImage")
        self.DispFrame = QtWidgets.QComboBox(self.centralwidget)
        self.DispFrame.setGeometry(QtCore.QRect(240, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DispFrame.setFont(font)
        self.DispFrame.setObjectName("DispFrame")
        self.DispFrame.addItem("")
        self.DispFrame.addItem("")
        self.DispFrame.addItem("")
        self.RecVideo = QtWidgets.QPushButton(self.centralwidget)
        self.RecVideo.setGeometry(QtCore.QRect(30, 570, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RecVideo.setFont(font)
        self.RecVideo.setCheckable(True)
        self.RecVideo.setObjectName("RecVideo")
        self.SaveImages = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImages.setGeometry(QtCore.QRect(200, 670, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveImages.setFont(font)
        self.SaveImages.setObjectName("SaveImages")
        self.NumImages = QtWidgets.QLineEdit(self.centralwidget)
        self.NumImages.setGeometry(QtCore.QRect(110, 700, 61, 31))
        self.NumImages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.NumImages.setObjectName("NumImages")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 670, 101, 61))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.TestPixels = QtWidgets.QPushButton(self.centralwidget)
        self.TestPixels.setGeometry(QtCore.QRect(30, 770, 311, 71))
        self.TestPixels.setObjectName("TestPixels")
        self.mplimg1 = MPLWidget(self.centralwidget)
        self.mplimg1.setGeometry(QtCore.QRect(370, 70, 750, 750))
        self.mplimg1.setAutoFillBackground(True)
        self.mplimg1.setObjectName("mplimg1")
        self.mplimg2 = MPLWidget(self.centralwidget)
        self.mplimg2.setGeometry(QtCore.QRect(1140, 70, 750, 750))
        self.mplimg2.setAutoFillBackground(True)
        self.mplimg2.setObjectName("mplimg2")
        self.mplhist1 = MPLWidget(self.centralwidget)
        self.mplhist1.setGeometry(QtCore.QRect(370, 860, 751, 191))
        self.mplhist1.setAutoFillBackground(True)
        self.mplhist1.setObjectName("mplhist1")
        self.mplhist2 = MPLWidget(self.centralwidget)
        self.mplhist2.setGeometry(QtCore.QRect(1140, 860, 751, 191))
        self.mplhist2.setAutoFillBackground(True)
        self.mplhist2.setObjectName("mplhist2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 40, 89, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1140, 40, 89, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 830, 89, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1140, 830, 89, 25))
        self.label_5.setObjectName("label_5")
        MBI_GUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(MBI_GUI)
        QtCore.QMetaObject.connectSlotsByName(MBI_GUI)

    def retranslateUi(self, MBI_GUI):
        _translate = QtCore.QCoreApplication.translate
        MBI_GUI.setWindowTitle(_translate("MBI_GUI", "MBI_GUI"))
        self.LoadBitFile.setText(_translate("MBI_GUI", "Load Bit File"))
        self.LoadPattFile.setText(_translate("MBI_GUI", "Load Camera Pattern File"))
        self.Exposure.setText(_translate("MBI_GUI", "1"))
        self.exposurelabel.setText(_translate("MBI_GUI", "Exposure Time [us]"))
        self.maskslabel.setText(_translate("MBI_GUI", "Masks"))
        self.Masks.setText(_translate("MBI_GUI", "600"))
        self.MaskChanges.setText(_translate("MBI_GUI", "0"))
        self.maskschangeslabel.setText(_translate("MBI_GUI", "Mask Changes"))
        self.maskschangeslabel_2.setText(_translate("MBI_GUI", "Subscenes per Change"))
        self.SubChange.setText(_translate("MBI_GUI", "0"))
        self.DispImage.setText(_translate("MBI_GUI", "Display Image"))
        self.DispFrame.setItemText(0, _translate("MBI_GUI", "ALL"))
        self.DispFrame.setItemText(1, _translate("MBI_GUI", "CEP"))
        self.DispFrame.setItemText(2, _translate("MBI_GUI", "CEP-TOF"))
        self.RecVideo.setText(_translate("MBI_GUI", "Record Video"))
        self.SaveImages.setText(_translate("MBI_GUI", "Save Images"))
        self.NumImages.setText(_translate("MBI_GUI", "1"))
        self.label.setText(_translate("MBI_GUI", "Number of Images"))
        self.TestPixels.setText(_translate("MBI_GUI", "Test Pixels"))
        self.label_2.setText(_translate("MBI_GUI", "TextLabel"))
        self.label_3.setText(_translate("MBI_GUI", "TextLabel"))
        self.label_4.setText(_translate("MBI_GUI", "TextLabel"))
        self.label_5.setText(_translate("MBI_GUI", "TextLabel"))

from mplwidget import MPLWidget
